export const USER_SINGUP_REQUEST = "USER_SINGUP_REQUEST";
export const USER_SINGUP_SUCCESS = "USER_SINGUP_SUCCESS";
export const USER_SINGUP_FAILURE = "USER_SINGUP_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
